Top4J CLI JVM selector menu enhancement: Remove JVM selection functionality from top4j wrapper script as this is now incorporated into Top4J Java class main method. Add additional local env checks to top4j wrapper script. MAX_THREAD_NAME_LENGTH used to drive CLI console screens from 49 to 64.

diff --git a/top4j-cli/src/main/scripts/top4j b/top4j-cli/src/main/scripts/top4j
--- a/top4j-cli/src/main/scripts/top4j
+++ b/top4j-cli/src/main/scripts/top4j
@@ -18,94 +18,52 @@
 #
 #        ./top4j 468
 #
+#    Environment Variable Prerequisites:
+#
+#      JAVA_HOME       Must point at your Java Development Kit installation.
+#
 
 JVM_PID=$1
-INSTALL_DIR=`dirname $0`
-LIB_DIR=${INSTALL_DIR}/../lib
-TOP4J_JAR=${LIB_DIR}/top4j-cli-0.0.4.jar
-JAVA_HOME=/usr/java/jdk1.8.0_60
-JCMD=${JAVA_HOME}/bin/jcmd
-JAVA=${JAVA_HOME}/bin/java
+INSTALL_DIR=`dirname $BASH_SOURCE`
+TOP4J_JAR=`ls -t ${INSTALL_DIR}/top4j-cli-[0-9]*.[0-9]*.[0-9]*.jar  | head -1`
+# NOTE: Override JAVA_HOME here if it's not part of the local runtime environment
+#JAVA_HOME=/usr/java/jdk1.8.0_60
+JAVA_BIN_DIR=${JAVA_HOME}/bin
+JAVA_LIB_DIR=${JAVA_HOME}/lib
+JAVA=${JAVA_BIN_DIR}/java
+TOOLS_JAR=${JAVA_LIB_DIR}/tools.jar
+
+# check JAVA_HOME
+if [[ -z ${JAVA_HOME} ]]
+then
+	echo "ERROR: JAVA_HOME environment variable NOT defined."
+	echo "HINT: A Java JDK installation is required to run this program. Please set JAVA_HOME env var to a local JDK installation location."
+	exit 1
+fi
 
 # check JAVA
 if [[ ! -x ${JAVA} ]]
 then
-	echo "ERROR: Java command not found under configured JAVA_HOME - ${JAVA_HOME}"
+	echo "ERROR: Java command not found under configured JAVA_HOME bin directory - ${JAVA_BIN_DIR}"
+	echo "HINT: A Java JDK installation is required to run this program. Please set JAVA_HOME env var to a local JDK installation location."
 	exit 1
 fi
 
 # check TOP4J_JAR
 if [[ ! -f ${TOP4J_JAR} ]]
 then
-	echo "ERROR: Top4j jar not found under configured TOP4J_JAR location - ${TOP4J_JAR}"
+	echo "ERROR: Top4j jar not found under top4j INSTALL_DIR location - ${INSTALL_DIR}"
 	exit 1
 fi
 
-function select-jvm-pid
-
-{
-
-# prompt user to select JVM PID
-
-declare -a JVM_PIDS
-declare -a JVM_CLASSES
-
-NUMBER_OF_JVMS=`${JCMD} | grep -v jcmd | wc -l`
-
-if [[ ${NUMBER_OF_JVMS} -eq 0 ]]
+# check TOOLS_JAR
+if [[ ! -f ${TOOLS_JAR} ]]
 then
-	echo "ERROR: No available JVMs detected using the jcmd command."
-	echo "HINT: Check you are running this script as the JVM process owner."
+	echo "ERROR: JDK tools.jar not found under JAVA_HOME lib directory - ${JAVA_LIB_DIR}."
+	echo "HINT: A Java JDK installation is required to run this program. Please set JAVA_HOME env var to a local JDK installation location."
 	exit 1
 fi
 
-JVM_PIDS=(`${JCMD} | gawk ' { print $1 } '`)
-JVM_CLASSES=(`${JCMD} | gawk ' { print $2 } '`)
-
-JVM_COUNT=0
-
-echo
-echo "The following JVMs are available:"
-echo
-
-for JVM_PID in ${JVM_PIDS[*]}
-do
-	echo "${JVM_COUNT}) ${JVM_CLASSES[${JVM_COUNT}]} [PID=${JVM_PID}]"
-	(( JVM_COUNT=JVM_COUNT+1 ))
-
-done
-
-echo
-
-while [[ -z ${JVM_NO} ]]
-do
-	echo -e "Please select a JVM number between 0 and $(($JVM_COUNT-1)): \c"
-        read JVM_NO
-	if [[ -z ${JVM_PIDS[$JVM_NO]} ]]
-	then
-		JVM_NO=""
-		continue
-	fi
-done
-
-echo "JVM PID ${JVM_PIDS[${JVM_NO}]} selected. Launching top4j...."
-
-JVM_PID=${JVM_PIDS[${JVM_NO}]}
-
-}
-
-
-# check args
-if [[ -z ${JVM_PID} ]]
-then
-	if [[ ! -x ${JCMD} ]]
-	then
-		echo "USAGE: $0 <jvm-pid>"
-		exit 1
-	else
-		select-jvm-pid
-	fi
-fi
 
 # launch top4j against JVM_PID
 ${JAVA} -jar ${TOP4J_JAR} ${JVM_PID}
